version: "3"

services:
  haproxy:
    image: haproxy:latest
    restart: always
    container_name: load-balancer
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl:/usr/local/etc/certs:ro
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend

  nginx-certbot:
    image: nginx
    restart: always
    container_name: nginx-certbot
    volumes:
      - ./webroot:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    networks: 
      - frontend

  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - frontend

networks:
  frontend: